** CUDA EXERCISES 5 AND 6 NON COMPUTED IN THIS NOTEBOOK BECAUSE THERE IS NO GPU ACCESSIBLE FROM THE LOCAL COMPUTER. RUN IN ANOTHER FILE WITH GOOGLE COLLAB

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
tensor = torch.rand(7, 7)
tensor, tensor.shape, tensor.ndim, tensor.dtype

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
         [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]]),
 torch.Size([7, 7]),
 2,
 torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor_2 = torch.rand(1, 7)
print(f"The new tensor of (1, 7) dimension is: \n {tensor_2}")
# Perform matrix multiplication 
multiplied = torch.matmul(tensor, tensor_2.T)
multiplied, multiplied.shape, multiplied.ndim, multiplied.dtype

The new tensor of (1, 7) dimension is: 
 tensor([[0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018]])


(tensor([[2.1685],
         [2.1932],
         [1.6342],
         [0.9317],
         [0.9952],
         [1.7791],
         [1.8525]]),
 torch.Size([7, 1]),
 2,
 torch.float32)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(seed=0)
# Create two random tensors
rand_1=torch.rand(7, 7)
rand_2=torch.rand(1, 7)
# Matrix multiply tensors
mult=torch.matmul(rand_1, rand_2.T)
mult, mult.shape, mult.ndim, mult.dtype

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]),
 2,
 torch.float32)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU


In [8]:
tensor_A=torch.tensor([[0.0290, 0.4019, 0.2598],
                    [0.3666, 0.0583, 0.7006]])
tensor_B=torch.tensor([[0.0518, 0.4681, 0.6738],
                    [0.3315, 0.7837, 0.5631]])
tensor_A, tensor_B, tensor_A.shape, tensor_B.shape

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
result=torch.matmul(tensor_A, tensor_B.T)
result, result.shape, result.ndim, result.dtype

(tensor([[0.3647, 0.4709],
         [0.5183, 0.5617]]),
 torch.Size([2, 2]),
 2,
 torch.float32)

### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
max=torch.max(result)
# Find min
min=torch.min(result)

max, min, result.max(), result.min()

(tensor(0.5617), tensor(0.3647), tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
arg_max=torch.argmax(result)

# Find arg min
arg_min=torch.argmin(result)

arg_max, arg_min, result.argmax(), result.argmin()

(tensor(3), tensor(0), tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.manual_seed(seed=7)

# Create random tensor
rand_tensor=torch.rand(1, 1, 1, 10)
# Remove single dimensions
reshaped_tensor=torch.squeeze(rand_tensor)

# Print out tensors and their shapes
print(f"The tensor created is {rand_tensor} with dimension {rand_tensor.shape}")
print(f"The tensor created is {reshaped_tensor} with dimension {reshaped_tensor.shape}")

The tensor created is tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) with dimension torch.Size([1, 1, 1, 10])
The tensor created is tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) with dimension torch.Size([10])
